apiVersion: v1
kind: PersistentVolume
metadata:
  name: host-pv
spec:
  capacity: 
    storage: 1Gi
  volumeMode: Filesystem
  storageClassName: standard
  accessModes:  #It is to tell how we want to claim a Volume
    - ReadWriteOnce #Only one node can claim this volume
    # - ReadOnlyMany  #Multiple Nodes can claim this volume
    # - ReadWriteMany #Same like above
  hostPath:
    path: /data
    type: DirectoryOrCreate